server:
  port: 8084

spring:
  application:
    name: serviceregistry

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: company_service
              uri: lb://COMPANY-SERVICE
              predicates:
                - Path=/companies/**

            - id: job_service
              uri: lb://JOB-SERVICE
              predicates:
                - Path=/jobs/**

            - id: review_service
              uri: lb://REVIEW-SERVICE
              predicates:
                - Path=/reviews/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
